#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "SquadAIAutoSetupManager.generated.h"

class ALeaderCharacter;
class AAllySoldier;
class AEnemySoldier;
class USquadAIPackValidationComponent;
class UBlueprint;

UCLASS(BlueprintType, Blueprintable)
class SQUADAI_API ASquadAIAutoSetupManager : public AActor
{
    GENERATED_BODY()

public:
    ASquadAIAutoSetupManager();

    virtual void BeginPlay() override;

#if WITH_EDITOR
    virtual void PostEditChangeProperty(struct FPropertyChangedEvent& PropertyChangedEvent) override;
#endif

    UFUNCTION(BlueprintCallable, CallInEditor, Category="SquadAI|Auto Setup")
    bool RunEditorAutoSetup();

    UFUNCTION(BlueprintCallable, CallInEditor, Category="SquadAI|Auto Setup")
    bool RunEditorValidation();

    UFUNCTION(BlueprintCallable, CallInEditor, Category="SquadAI|Asset Factory")
    UBlueprint* CreateLeaderBlueprintAsset();

    UFUNCTION(BlueprintCallable, CallInEditor, Category="SquadAI|Asset Factory")
    UBlueprint* CreateAllyBlueprintAsset();

    UFUNCTION(BlueprintCallable, CallInEditor, Category="SquadAI|Asset Factory")
    UBlueprint* CreateEnemyBlueprintAsset();

    UFUNCTION(BlueprintCallable, CallInEditor, Category="SquadAI|Auto Setup")
    FString BuildSetupSummary();

    UFUNCTION(BlueprintCallable, BlueprintPure, Category="SquadAI|Diagnostics")
    static bool AreVerboseDebugLogsEnabled();

protected:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Auto Setup")
    bool bRunInEditorOnly = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Auto Setup")
    bool bRunOnBeginPlay = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Auto Setup")
    bool bDisableAfterSuccessfulSetup = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Auto Setup")
    bool bValidateAfterSetup = true;

    // Enables very noisy diagnostic logs across SquadAI combat/perception/cover/TPWCS bridge code.
    // Keep this OFF normally. Turn it ON only for short PIE tests when we need detailed traces.
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Diagnostics")
    bool bEnableVerboseDebugLogs = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Discovery")
    ALeaderCharacter* ExplicitLeader = nullptr;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Discovery")
    TArray<AAllySoldier*> ExplicitAllies;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Discovery")
    TArray<AEnemySoldier*> ExplicitEnemies;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Discovery")
    bool bAutoFindLeaderIfMissing = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Discovery")
    bool bAutoFindAlliesIfArrayEmpty = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Discovery")
    bool bAutoFindEnemiesIfArrayEmpty = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Discovery")
    FName RequiredActorTag;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Asset Factory")
    FString AssetPackagePath = TEXT("/Game/_AutoGeneratedSquadAI");

    // Better TPWCS integration path: duplicate a known-working pack AI BP and add only SquadAI brain helpers.
    // Screenshots show BP_AICharacter as the normal clean AI template. BP_AICharacter_Blank has extra sample logic,
    // and BP_AICharacter_Test is explicitly a testing class with random weapon logic.
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Asset Factory|Pack Template")
    bool bCreateBlueprintsFromPackTemplates = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Asset Factory|Pack Template")
    FString LeaderPackTemplateAssetName = TEXT("BP_AICharacter");

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Asset Factory|Pack Template")
    FString AllyPackTemplateAssetName = TEXT("BP_AICharacter");

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Asset Factory|Pack Template")
    FString EnemyPackTemplateAssetName = TEXT("BP_AICharacter");

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Asset Factory")
    FString LeaderAssetName = TEXT("BP_Leader_PackClean_Auto");

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Asset Factory")
    FString AllyAssetName = TEXT("BP_Ally_PackClean_Auto");

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Asset Factory")
    FString EnemyAssetName = TEXT("BP_Enemy_PackClean_Auto");

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Editor Actions")
    bool bExecuteCreateLeaderBlueprint = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Editor Actions")
    bool bExecuteCreateAllyBlueprint = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Editor Actions")
    bool bExecuteCreateEnemyBlueprint = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Editor Actions")
    bool bExecuteRunEditorAutoSetup = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Editor Actions")
    bool bExecuteRunEditorValidation = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SquadAI|Editor Actions")
    bool bExecuteBuildSetupSummary = false;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="SquadAI|Editor Actions")
    FString LastSetupSummary;

    UPROPERTY(VisibleInstanceOnly, BlueprintReadOnly, Category="SquadAI|Auto Setup")
    bool bSetupAlreadyCompleted = false;

private:
    ALeaderCharacter* ResolveLeader() const;
    TArray<AActor*> ResolveAllies() const;
    TArray<AActor*> ResolveEnemies() const;
    void DisableManagerIfNeeded();
};
