// WaveSpawner.h — Timer-driven wave spawner with pool support + NavMesh projection
// Spawns enemies in batches across waves. Uses EnemyPool if available.
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "SquadTypes.h"
#include "Quest/QuestTypes.h"
#include "WaveSpawner.generated.h"

class UWaveTemplate;
class AEnemyAttackCoordinator;

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnWaveStarted, int32, WaveIndex);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnWaveCleared, int32, WaveIndex);
DECLARE_DYNAMIC_MULTICAST_DELEGATE(FOnAllWavesCleared);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnEnemySpawned, APawn*, Enemy);

UCLASS(BlueprintType, Blueprintable)
class SQUADAI_API AWaveSpawner : public AActor
{
	GENERATED_BODY()

public:
	AWaveSpawner();

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spawner")
	FQuestTag SpawnerTag;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spawner")
	TObjectPtr<UWaveTemplate> WaveTemplate;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spawner")
	TSubclassOf<APawn> DefaultEnemyClass;
	
	// AUTO-LYRA SETUP: If true, the spawner will start automatically on BeginPlay.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spawner")
	bool bAutoStartOnBeginPlay = false;

	// Spawn point locations (auto-generated by AutoSpawnZone, or set manually)
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spawner", meta = (MakeEditWidget = true))
	TArray<FVector> SpawnPointLocations;

	// NavMesh projection extent for spawn validation
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spawner")
	float SpawnPointSearchExtent = 120.f;

	// Optional coordinator to assign spawned enemies to
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spawner")
	TWeakObjectPtr<AEnemyAttackCoordinator> Coordinator;

	// ---- Runtime ----
	UPROPERTY(BlueprintReadOnly, Category = "Spawner|Runtime")
	int32 CurrentWaveIndex = -1;

	UPROPERTY(BlueprintReadOnly, Category = "Spawner|Runtime")
	int32 CachedLiving = 0; // O(1) read — death-driven decrement

	UPROPERTY(BlueprintReadOnly, Category = "Spawner|Runtime")
	int32 TotalSpawned = 0;

	UPROPERTY(BlueprintReadOnly, Category = "Spawner|Runtime")
	int32 TotalKilled = 0;

	// ---- Events ----
	UPROPERTY(BlueprintAssignable) FOnWaveStarted OnWaveStarted;
	UPROPERTY(BlueprintAssignable) FOnWaveCleared OnWaveCleared;
	UPROPERTY(BlueprintAssignable) FOnAllWavesCleared OnAllWavesCleared;
	UPROPERTY(BlueprintAssignable) FOnEnemySpawned OnEnemySpawned;

	// ---- API ----
	UFUNCTION(BlueprintCallable, Category = "Spawner")
	void StartWaves();

	UFUNCTION(BlueprintCallable, Category = "Spawner")
	void StopWaves();

	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "Spawner")
	bool AreAllWavesComplete() const;

	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "Spawner")
	int32 GetTotalWaveCount() const;

protected:
	virtual void BeginPlay() override;
	virtual void EndPlay(const EEndPlayReason::Type Reason) override;

private:
	UPROPERTY() TArray<TWeakObjectPtr<APawn>> AllSpawned;

	// Wave state
	int32 SpawnedThisWave = 0;
	int32 TargetThisWave = 0;
	int32 BatchesDone = 0;
	bool bSpawningActive = false;

	FTimerHandle WaveDelayTimer;
	FTimerHandle BatchTimer;

	void StartNextWave();
	void SpawnNextBatch();
	APawn* SpawnOneEnemy(TSubclassOf<APawn> Class);
	FVector GetNextSpawnLocation();
	int32 SpawnPointRoundRobin = 0;

	UFUNCTION()
	void HandleSpawnedDied(AActor* DeadActor);

	void CompactStaleRefs();
};
